163 adding risk adjustment example
tuva-health/knowledge_base pull request #167
Opened 2023-10-17 21:44 UTC by chase-jones

@sarah-tuva pinging for awareness. This is first pass at providing single patient example for this issue. Open to feedback or changes you would like.

@aneiderhiser Let me know if this has the types of graphics / charts you were envisioning.

2023-10-17 22:05 UTC, aneiderhiser commented
@chase-jones this is AWESOME!  Fantastic addition.  I'm going to merge this.  Then I have a couple thoughts on re-organizing a few things that I'll open a separate PR for.

2023-10-17 22:09 UTC, sarah-tuva requested changes
@chase-jones Incredible job! 👏  Thank you so much for your work in putting this example together with screenshots. I can imagine how much time this took. I just saw a few typos at the end. I even learned a few things. Thanks again! 🙌

2023-10-17 22:09 UTC, sarah-tuva commented on docs/risk-adjustment/cms-hccs.md
> +What does this mean? This means we have to go back and repeat the steps prior to "Brining it all together"
```suggestion
What does this mean? This means we have to go back and repeat the steps prior to "Bringing it all together"
```

2023-10-18 01:43 UTC, chase-jones commented
Glad to hear it! There's still some outstanding detail here that is missing, but not sure how that is a priority for you all or if I should make it an issue.

Some examples (off the top of my head and in no particular order):

* Date ranges and dates of service 
* MMR initial enrollment and 26 sweep 
* How age is exactly determined
* Rounding / sig figs
* Nitty gritty in regards to eligibility

2023-10-18 04:54 UTC, aneiderhiser commented
@chase-jones those add'l details all make sense to me.  Feel free to create an issue to keep track.  

I'll let @sarah-tuva re-review your latest commit and then we can merge this in.

2023-10-18 14:26 UTC, sarah-tuva approved these changes
Looks great to me! I can merge it in if we're ready to go. It sounds like we'll create an issue to track the additional examples we want to add. Thanks again @chase-jones! 🌟

2023-10-18 15:24 UTC, merged